# Setup
title:        Switcher 的博客
tagline:      关于 Switcher 的信息，都在这里
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       AASQuanDeng
  url:        https://github.com/AASQuanDeng/AAS/tree/Switcher 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown