# Setup
title:        Switcher Blogs
tagline:      The Official Site Of Switcher
baseurl:      "https://www.github.com/AASQuanDeng/AAS/tree/Switcher"
paginate:     1
locale:       "cn"

# About/contact
author:
  name:       AASQuanDeng
  url:        https://github.com/AASQuanDeng 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
